### ISSUE TITLE
[Bug] Unable to connect to ollama.

### ISSUE THREAD

**Issue by wwjCMP** [taichimaeda/markpilot#6]
## Actual Behavior
I used http://192.168.101.19:11434, but the connection failed.
## Specifications

- Version: 1.2.3
- Platform: window
- Subsystem: linux

**Comment by taichimaeda** [comment]
Thanks for raising this.

I cannot reproduce this in my environment, so do you mind opening the devtools (`Ctrl+Shift+i`) and take a screenshot of whatever the error message you see in the "Console" tab?

**Comment by wwjCMP** [comment]
![image](https://github.com/taichimaeda/markpilot/assets/32979859/9b3f6f5f-c2e1-4a97-b3f3-2dd8388dfde5)

**Comment by taichimaeda** [comment]
This is just my guess but 404 seems to suggest that the model is not available?

Make sure you have pulled the model in the terminal:

```console
$ ollama pull --model llama2
$ ollama serve
```

**Comment by wwjCMP** [comment]
The models I installed are not the standard versions, could this be the problem?

**Comment by taichimaeda-ca** [comment]
That's likely the issue, would you mind sharing the model and its version you're using?

**Comment by taichimaeda** [comment]
Thant's likely the case, do you mind letting me know the model and its version you're using so I can have a look?

**Comment by wwjCMP** [comment]
![image](https://github.com/taichimaeda/markpilot/assets/32979859/359a5054-3bc2-417d-adb3-a809f9858d54)

**Comment by taichimaeda** [comment]
Makes sense. Since the current version of the plugin does not specify the tag, it seems to fallback to `latest`.

I've just pushed [48c9f28](https://github.com/taichimaeda/markpilot/commit/48c9f28f4a9187fd2cfe340f1f6404cad92cb997) which includes a setting to specify the model tag for Ollama. I'll release a new version after a bit more testing, hopefully this should fix it!
